AWSTemplateFormatVersion: '2010-09-09'
Description: root stack for parity in ECS

Parameters:
  KeyName:
    Type: String

  SecurityGroup:
    Type: String

  Subnet:
    Type: String

Mappings:
  AWSRegionToAMI:
    us-east-2:
      AMI: ami-028a9de0a7e353ed9
    us-east-1:
      AMI: ami-00129b193dc81bc31
    us-west-2:
      AMI: ami-00d4f478
    us-west-1:
      AMI: ami-0d438d09af26c9583
    eu-west-3:
      AMI: ami-07da674f0655ef4e1
    eu-west-2:
      AMI: ami-a44db8c3
    eu-west-1:
      AMI: ami-0af844a965e5738db
    eu-central-1:
      AMI: ami-0291ba887ba0d515f
    ap-northeast-2:
      AMI: ami-047d2a61f94f862dc
    ap-northeast-1:
      AMI: ami-0041c416aa23033a2
    ap-southeast-2:
      AMI: ami-0092e55c70015d8c3
    ap-southeast-1:
      AMI: ami-091bf462afdb02c60
    ca-central-1:
      AMI: ami-192fa27d
    ap-south-1:
      AMI: ami-0c179ca015d301829
    sa-east-1:
      AMI: ami-0018ff8ee48970ac3
    us-gov-west-1:
      AMI: ami-c6079ba7

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AWSRegionToAMI, !Ref "AWS::Region", AMI]
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      Tags:
        - Key: Purpose
          Value: "SSH Bastion Host"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - !Ref SecurityGroup
          SubnetId: !Ref Subnet
Outputs:
  InstanceId:
    Value: !Ref Instance

  PublicDNSName:
    Value: !GetAtt Instance.PublicDnsName
