AWSTemplateFormatVersion: '2010-09-09'
Description: ECS cluster running single Parity node
Parameters:
  Namespace:
    Type: String

  VPC:
    Type: AWS::EC2::VPC::Id

  Cluster:
    Type: String

  DesiredTaskCount:
    Type: Number

  ALBListener:
    Description: Application Load Balancer listener to register with
    Type: String

  Path:
    Description: path to register with the Application Load Balancer
    Type: String

  ParityClientRepositoryName:
    Type: String

  EthIndexerRepositoryName:
    Type: String

  NginxRepositoryName:
    Type: String

  NetworkName:
    Type: String

  IndexerStartBlock:
    Type: Number

  IndexerConfirmationHeight:
    Type: Number

  IndexerAPIKeyS3Path:
    Type: String
    Default: ""

Conditions:
  ApiIsPrivate: !Not [!Equals [!Ref IndexerAPIKeyS3Path, ""]]

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Port: 80 # will be overridden when ECS registers a task as a target
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: !Sub /health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2

  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ALBListener
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - !Join ["/", [!Ref Path, "*"]]
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward

  ECSService:
    Type: AWS::ECS::Service
    DependsOn: ALBListenerRule
    Properties:
      # DeploymentConfiguration:
      #   MaximumPercent: 100
      #   # allow ECS to undeploy first
      #   MinimumHealthyPercent: 0

      # custom name makes it hard to update the stack, giving errors like this:
      #
      #   CloudFormation cannot update a stack when a custom-named resource requires replacing.
      #   Rename parity-ropsten-1|parity-ropsten-1-service and update the stack again.
      #
      # ServiceName: !Sub ${Namespace}-service
      Cluster: !Ref Cluster
      Role: !Ref ServiceRole
      DesiredCount: !Ref DesiredTaskCount
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: nginx-proxy
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup

  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${Namespace}-nginx-service-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ecs-service
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - elasticloadbalancing:Describe*
                  - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
                  - elasticloadbalancing:RegisterInstancesWithLoadBalancer
                  - ec2:Describe*
                  - ec2:AuthorizeSecurityGroupIngress
                  - elasticloadbalancing:RegisterTargets
                  - elasticloadbalancing:DeregisterTargets
                Resource: '*'

  TaskRole:
    Type: AWS::IAM::Role
    Condition: ApiIsPrivate
    Properties:
      Path: /
      RoleName: !Sub ${Namespace}-task-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: api-key-access
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:HeadObject
                  - s3:GetObject
                Resource: !Sub arn:aws:s3:::${IndexerAPIKeyS3Path}

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: eth
      TaskRoleArn: !If
        - ApiIsPrivate
        - !Ref TaskRole
        - !Ref "AWS::NoValue"
      NetworkMode: bridge
      ContainerDefinitions:
        - Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${NginxRepositoryName}:latest
          Essential: true
          Cpu: 256
          Memory: 256
          Name: nginx-proxy
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          Links:
            - eth-indexer
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: nginx-proxy
          Environment:
            - Name: ETH_INDEXER_HOST
              Value: eth-indexer:3000
            - Name: PARITY_HOST
              Value: parity:8545
            - Name: S3_PATH_TO_API_KEY
              Value: !Ref IndexerAPIKeyS3Path
            - Name: ETH_NETWORK
              Value: !Ref NetworkName

        - Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ParityClientRepositoryName}:latest
          Essential: true
          Memory: 3000
          MemoryReservation: 1000
          Name: parity
          PortMappings:
            - ContainerPort: 8545
              HostPort: 0
              Protocol: tcp
            - ContainerPort: 8546
              HostPort: 0
              Protocol: tcp
            - ContainerPort: 30303
              HostPort: 0
              Protocol: tcp
            - ContainerPort: 30303
              HostPort: 0
              Protocol: udp
          MountPoints:
            - ContainerPath: /root/.local/share/io.parity.ethereum/chains
              SourceVolume: parity-chains
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: parity
          Environment:
              - Name: 'NETWORK_NAME'
                Value: !Ref NetworkName
          #   - Name: "TARGET_BLOCK"
          #     Value: "1"

        - Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EthIndexerRepositoryName}:latest
          Essential: true
          Memory: 1000
          MemoryReservation: 512
          Name: eth-indexer
          PortMappings:
            - ContainerPort: 3000
              HostPort: 0
              Protocol: tcp
          MountPoints:
            - ContainerPath: /root/.eth-indexer/
              SourceVolume: eth-indexes
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: eth-indexer
          Links:
            - parity
          Environment:
            - Name: 'NODE_NETWORK'
              Value: !Ref NetworkName
            - Name: 'NODE_HOSTNAME'
              Value: 'parity'
            - Name: 'NODE_HTTP_PORT'
              Value: '8545'
            # - Name: 'NODE_WS_PORT'
            #   Value: '8546'
            # - Name: 'SERVER_BASE_PATH'
            #   Value: !Ref Path
            # gets stuck periodically otherwise
            - Name: 'NODE_USE_WS'
              Value: 'false'
            - Name: 'START_BLOCK'
              Value: !Ref IndexerStartBlock
            - Name: 'CONFIRMATION_HEIGHT'
              Value: !Ref IndexerConfirmationHeight
            - Name: 'DEBUG'
              Value: 'tradle:*'

      Volumes:
        - Host:
            SourcePath: /data/chains
          Name: parity-chains
        - Host:
            SourcePath: /data/indexes
          Name: eth-indexes

        # - ContainerName: parity
        #   ContainerPort: 8545
        #   TargetGroupArn: !Ref JsonRpcTargetGroup

      # TaskDefinition: !Join [ "", ['arn:aws:ecs:', !Ref "AWS::Region", ':', !Ref "AWS::AccountId", ':task-definition/parity:1']]

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 1

Outputs:
  ECSService:
    Description: ECS service for Ethereum indexer and full node
    Value: !Ref ECSService
