#!/bin/bash

source scripts/.env

PARAMS=${1-../cloudformation/stack-parameters-update.json}
aws cloudformation update-stack \
  --profile $AWS_PROFILE \
  --stack-name $STACK_NAME \
  --template-body file://`pwd`/service-template.yml \
  --parameters file://`pwd`/$PARAMS \
  --capabilities CAPABILITY_NAMED_IAM
